name: Test image build on push or PR
on:
  push:
    branches:
      - master
    paths:
      - 'pi-gen/**'
      - 'packages/**'
      - '.github/workflows/on-push.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'pi-gen/**'
      - 'packages/**'
      - '.github/workflows/on-push.yml'

jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: pi-gen

      steps:
      - uses: actions/checkout@v4

      - name: Register binfmt_misc entries
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run build script
        run: sudo PIGEN_DOCKER_OPTS="-e DEPLOY_XZ=1" ./build-docker.sh

      - name: List deploy directory
        run: ls -al deploy/
